=== Butterfly3108/wba2_2_studynews/wba22_studynews/bin/xmlUxsd/dozent/dozent.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	 
	elementFormDefault="qualified">
				
	<xs:element name="dozent">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ct_dozent">
					<xs:attribute name="id" type="xs:nonNegativeInteger"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="ct_dozent">
		<xs:sequence>
			<xs:element name="titel" type="xs:string" />
			<xs:element name="adresse" type="ct_adresse"/>
			<xs:element name="lehre" type="ct_lehre"/>
			<xs:element name="newsticker" type="ct_newsticker"/>
			<xs:element name="abonnenten" type="ct_abonnenten"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ct_adresse">
		<xs:sequence>
		<xs:element name="anschrift" type="xs:string" />
			<xs:element name="raumnr">
				<xs:complexType>
					<xs:attribute name="nummer" type="xs:nonNegativeInteger" />
				</xs:complexType>
			</xs:element>
			<xs:element name="tel">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="nummer" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="art" type="xs:string" />
								<xs:attribute name="nr" type="xs:string" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="email">
				<xs:complexType>
					<xs:attribute name="adresse" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>	
	
	<xs:complexType name="ct_lehre">
		<xs:sequence>
			<xs:element name="lehrgebiet" type="xs:string" />
			<xs:element name="schwerpunkte" type="xs:string" minOccurs="0" />
			<xs:element name="url" type="xs:string" />
			<xs:element name="sprechzeit" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="veranstaltungen">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="bezeichnung" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ct_newsticker">
		<xs:sequence>
			<xs:element name="eintrag" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="datum" type="xs:date" />
					<xs:attribute name="verfasser" type="xs:string" />
					<xs:attribute name="modul" type="xs:string" />
					<xs:attribute name="text" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ct_abonnenten">
		<xs:sequence>
			<xs:element name="abonnent" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="name" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Butterfly3108/wba2_2_studynews/wba22_studynews/src/xmlUxsd/dozent/5.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<dozent xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="5" xsi:schemaLocation="http://example.org/dozent ../xmlUxsd/dozent/dozent.xsd">
    <titel>Max Mustermann</titel>
    <adresse>
        <anschrift>MusterstraÃŸe 1, 11111 Musterhausen</anschrift>
        <raum>1111</raum>
        <tel>314872393</tel>
        <email>mustermann at gm.fh-koeln.de</email>
    </adresse>
    <lehre>
        <lehrgebiet>Musterlehre</lehrgebiet>
        <url>http://www.gm.fh-koeln.de/~mustermann</url>
        <veranstaltungen>
            <list kuerzel="ML">Musterlehre</list>
        </veranstaltungen>
    </lehre>
    <newsticker>
        <eintrag modul="ML" verfasser="Max Mustermann" datum="2013-05-06">Bla bla</eintrag>
        <eintrag modul="ML" verfasser="Max Mustermann" datum="2013-05-28">testinfo</eintrag>
        <eintrag modul="ML" verfasser="Max Mustermann" datum="2013-05-28+02:00">test test</eintrag>
    </newsticker>
    <abonnenten/>
</dozent>

=== Butterfly3108/wba2_2_studynews/wba22_studynews/src/xml/dozent/3.xml
<?xml version="1.0" encoding="UTF-8"?>
<dozent id="3" xmlns="http://www.example.org/dozent" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://example.org/dozent ../../xsd/dozent.xsd ">
		<titel>Prof. Dr. Horst Stenzel</titel>
		<adresse titel="Adresse">
			<anschrift>Steinmüllerallee 1, 51643 Gummersbach</anschrift>
			<raum titel="Raum" nummer="3207" />
			<tel>
				<nummer art="Telefon" nr="+49 2261 8196 6403" />
				<nummer art="Fax" nr="+49 2261 8196 6666" />
			</tel>
			<email adresse="stenzel at gm.fh-koeln.de" />
		</adresse>
		<lehre>
			<lehrgebiet>Angewandte Mathematik und Informatik</lehrgebiet>
			<schwerpunkte>Algortihmen für Computer-Graphik und Betriebssysteme</schwerpunkte>
			<url>http://www.gm.fh-koeln.de/hstl</url>
			<sprechzeit>dienstags 14:00 - 14:45 Uhr</sprechzeit>
			<veranstaltungen>
				<list kuerzel="BS1">Betriebssysteme und verteilte Systeme</list>
			</veranstaltungen>
		</lehre>
		<newsticker titel="Newsticker">
			<eintrag datum="2013-05-10" verfasser="Prof. Dr. Horst Stenzel" modul="BS1" text="Am Freitag den 17.05.2013 findet die Vorlesung diesmal außerplanmäßig in Raum 0401 statt." />
			<eintrag datum="2013-04-01" verfasser="Prof. Dr. Horst Stenzel" modul="BS1" text="Die Staffelpläne sine online! Ab nächster Woche beginnt das Praktikum" />
			<eintrag datum="2013-03-22" verfasser="Prof. Dr. Horst Stenzel" modul="BS1" text="Organisation und Gruppeneinteilung für die Praktika!" />
		</newsticker>
		<abonnenten>
			<abonnent name="Daniela Kucharczyk" />
		</abonnenten>
</dozent>

=== Butterfly3108/wba2_2_studynews/wba22_studynews/src/xml/dozent/2.xml
<?xml version="1.0" encoding="UTF-8"?>
<dozent id="2" xmlns="http://www.example.org/dozent" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://example.org/dozent ../../xsd/dozent.xsd ">
		<titel>Prof. Dr. rer. nat. Wolfgang Konen</titel>
		<adresse titel="Adresse">
			<anschrift>Steinmüllerallee 1, 51643 Gummersbach</anschrift>
			<raum titel="Raum" nummer="3230" />
			<tel>
				<nummer art="Telefon" nr="+49 2261 8196 6275" />
				<nummer art="Fax" nr="+49 2261 8196 6666" />
			</tel>
			<email adresse="konen at gm.fh-koeln.de" />
		</adresse>
		<lehre>
			<lehrgebiet>Mathematik, Angewandte Informatik</lehrgebiet>
			<url>http://www.gm.fh-koeln.de/~konen/</url>
			<sprechzeit>mittwochs 13:15 - 14:00 Uhr</sprechzeit>
			<veranstaltungen>
				<list kuerzel="MA2">Mathematik 2</list>
			</veranstaltungen>
		</lehre>
		<newsticker titel="Newsticker">
			<eintrag datum="2013-04-0" verfasser="Prof. Dr. rer. nat. Wolfgang Konen" modul="MA2" text="Klausurergebnisse sind da!"/>
			<eintrag datum="2013-03-14" verfasser="Prof. Dr. rer. nat. Wolfgang Konen" modul="MA2" text="Diese Woche Beginn meiner Lehrveranstaltung!" />
			<eintrag datum="2013-03-10" verfasser="Prof. Dr. rer. nat. Wolfgang Konen" modul="MA2" text="Mi, 20.03.2013, 11 Uhr, ist pflichttermin Einführung MA2-Praktikum!" />
			<eintrag datum="2013-02-28" verfasser="Prof. Dr. rer. nat. Wolfgang Konen" modul="MA2" text="Klausurabgrenzung zur Klausur am 12.03.2013. Viel Erfolg!" />
		</newsticker>
		<abonnenten>
			<abonnent name="Daniela Kucharczyk" />
		</abonnenten>
</dozent>

=== Butterfly3108/wba2_2_studynews/wba22_studynews/src/xmlUxsd/dozent/6.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<dozent xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="6" xsi:schemaLocation="http://example.org/dozent ../xmlUxsd/dozent/dozent.xsd">
    <titel>MaxMustermann</titel>
    <adresse>
        <anschrift>Steinm√ºllerallee 1, 51643 Gummersbach</anschrift>
        <raum>1111</raum>
        <tel>2111111</tel>
        <email>Mustermann at gm.fh-koeln.de</email>
    </adresse>
    <lehre>
        <lehrgebiet></lehrgebiet>
        <url>http://www.gm.fh-koeln.de/~Mustermann</url>
        <veranstaltungen/>
    </lehre>
    <newsticker>
        <eintrag modul="ML" verfasser="MaxMustermann" datum="2013-05-28+02:00">info</eintrag>
        <eintrag modul="ML" verfasser="MaxMustermann" datum="2013-05-29+02:00">bla bla</eintrag>
        <eintrag modul="ML" verfasser="MaxMustermann" datum="2013-05-29+02:00">test bla bla</eintrag>
    </newsticker>
    <abonnenten/>
</dozent>
