=== Butterfly3108/wba2_2_studynews/wba22_studynews/src/xmlUxsd/userDatabase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	
	<xs:element name="userDatabase">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="eintrag" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nachname" type="xs:string" />
							<xs:element name="vorname" type="xs:string" />
							<xs:element name="status" type="xs:string" />
						</xs:sequence>
						<xs:attribute name="id" type="xs:integer" />	
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== Butterfly3108/wba2_2_studynews/wba22_studynews/bin/xmlUxsd/userDatabase.xml
<?xml version="1.0" encoding="UTF-8"?>
<userDatabase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="userDatabase.xsd">
    <eintrag id="1">
        <nachname>Fischer</nachname>
        <vorname>Kristian</vorname>
        <status>dozent</status>
    </eintrag>
    <eintrag id="2">
        <nachname>Konen</nachname>
        <vorname>Wolfgang</vorname>
        <status>dozent</status>
    </eintrag>
    <eintrag id="3">
        <nachname>Stenzel</nachname>
        <vorname>Horst</vorname>
        <status>dozent</status>
    </eintrag>
    <eintrag id="4">
        <nachname>Noss</nachname>
        <vorname>Christian</vorname>
        <status>dozent</status>
    </eintrag>
    <eintrag id="5">
        <nachname>Kucharczyk</nachname>
        <vorname>Daniela</vorname>
        <status>student</status>
    </eintrag>
    <eintrag id="6">
        <nachname>Will</nachname>
        <vorname>Paul</vorname>
        <status>student</status>
    </eintrag>
    <eintrag id="7">
        <nachname>admin</nachname>
        <vorname>admin</vorname>
        <status>admin</status>
    </eintrag>
</userDatabase>
