=== Butterfly3108/wba2_2_studynews/wba22_studynews/bin/xmlUxsd/dozentenliste.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	
	<xs:element name="dozentenliste">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="dEintrag" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="dozent_id" type="xs:nonNegativeInteger" />
							<xs:element name="name" type="xs:string" />
							<xs:element name="lehrgebiet" type="xs:string" />
							</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>



</xs:schema>

=== Butterfly3108/wba2_2_studynews/wba22_studynews/bin/xmlUxsd/dozentenliste.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<dozentenliste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://example.org/dozent ../xmlUxsd/dozentenliste.xsd">
    <dEintrag dozentId="1">
        <name>Prof. Dr. Kristian Fischer</name>
    </dEintrag>
    <dEintrag dozentId="2">
        <name>Prof. Dr. rer. nat. Wolfgang Konen</name>
    </dEintrag>
    <dEintrag dozentId="3">
        <name>Prof. Dr. Horst Stenzel</name>
    </dEintrag>
    <dEintrag dozentId="4">
        <name>Prof. Dipl. Des. Christian Noss</name>
    </dEintrag>
</dozentenliste>
