=== Butterfly3108/wba2_2_studynews/wba22_studynews/bin/xmlUxsd/modulliste.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	
	<xs:element name="modulliste">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="mEintrag" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="zustand" type="st_zustand" />
							<xs:element name="bezeichnung" type="xs:string" />
						</xs:sequence>
						<xs:attribute name="modulId" type="xs:integer" />	
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:simpleType name="st_zustand">
		<xs:restriction base="xs:string">
			<xs:enumeration value="online" />
			<xs:enumeration value="offline" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== Butterfly3108/wba2_2_studynews/wba22_studynews/bin/xmlUxsd/modulliste.xml
<?xml version="1.0" encoding="UTF-8"?>
<modulliste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://example.org/modul ../xmlUxsd/modulliste.xsd">
	<mEintrag modulId="1">
		<zustand>online</zustand>
		<bezeichnung>Web-basierte Anwendungen 2: Verteilte Systeme</bezeichnung>
	</mEintrag>
	<mEintrag modulId="2">
		<zustand>offline</zustand>
		<bezeichnung>EinfÃ¼hrung in die Medieninformatik</bezeichnung>
	</mEintrag>
	<mEintrag modulId="3">
		<zustand>online</zustand>
		<bezeichnung>Grundlagen der visuellen Kommunikation</bezeichnung>
	</mEintrag>
	<mEintrag modulId="4">
		<zustand>online</zustand>
		<bezeichnung>Mathematik 2</bezeichnung>
	</mEintrag>
	<mEintrag modulId="5">
		<zustand>online</zustand>
		<bezeichnung>Betriebssysteme und verteilte Systeme</bezeichnung>
	</mEintrag>
</modulliste>
